### PR TITLE
New output formatting

### PR DESCRIPTION
**Pull request by boyercb**
This PR adds improved output formatting to all logic checks, including:

- automatic column width adjustments
- "greying out" of repeated information
- fix to SurveyCTO links so they are proper URL links
- smart grouping and formatting to make outputs easier to read

### CODE REVIEW

**Comment by rsandino** [comment]
There is an extra replace in the ipacheckcomplete because the file needs to be replaced at some point for the mata formatting issue. I put it in ipacheckcomplete originally until we could talk about the best way to make sure the file is replaced every time it is run, so that the mata doesn't overwrite itself until the file crashes.

**Comment by boyercb** [comment]
@rsandino thinking about the issue with the extra replace... this might get solved with @iabaako's idea about creating a tempfile to write to during execution of the checks and then just moving this file to the appropriate path at the end. By definition that tempfile would be a new file each time you run and I don't think we'll run into the same issue.

**Comment by boyercb** [comment]
We need to update the reference in `master_check.do` to `ipachecklogic` and should perhaps change the name of the tab in the inputs sheet to match.

**Comment by boyercb** [comment]
> We need to update the reference in `master_check.do` to `ipachecklogic` and should perhaps change the name of the tab in the inputs sheet to match.

This is now done!

**Pull request merged**
