### PR TITLE
Test that required commands are installed

### PR DESCRIPTION
**Pull request by kbjarkefur**
The HFC tests requires three commands `cfout`, `bcstats`, and `readreplace` to be already instealled. This PR adds code that checks if the commands are installed and provides the code necessary to install them if they are not.

This solves something that @luizaandrade found when testing this package, and since I had code from another thing that would solve this I thought I should just send a PR.

Two things I am not sure of:
1. Do you want me to create a PR directly to the `master` branch in the future or do you have a different best practice for that? Feel free to change the branch this PR is currently set to merge to if you want.
1. It might be better to put this code inside `ipadoheader`, but only if that command is specific to the HFC package, since those three commands might not be needed for other things that command is used for, if it is intended to be used in other contexts as well. Let me know if you want me to move this code into `ipadoheader` instead.

### CODE REVIEW

**Comment by kbjarkefur** [comment]
is there a reason why you recommend installing _bcstats_ with `net install bcstats, replace from("https://raw.githubusercontent.com/PovertyAction/bcstats/master/ado")` and not `ssc install bcstats` here; https://povertyaction.force.com/support/s/article/ipa-user-written-Stata-commands ?

The ssc installation would make it possible to make the code in the PR much neater.

**Comment by rsandino** [comment]
Hey Kris, the reason we use the IPA Github is because it includes the -reliability- option when analyzing back checks, which is not included in the ssc version.

**Comment by rsandino** [comment]
One solution would be to just add the installation of those commands when ipacheck is installed, we're looking into that now. I think a check is still fine, but it might be cleaner to have it in ipadoheader instead of master_check?

**Comment by kbjarkefur** [comment]
Hey @rsandino, is the **reliability** option needed for `ipacheck`? Obviously up to you, but I would be careful of the confusing error that would be the result from someone having the *ssc* version installed when the *GitHub* version is needed, or vice versa. If the **reliability** option is not needed then the this concern is not relevant.

**Comment by kbjarkefur** [comment]
@rsandino , I agree that it is cleaner to do it inside of the `ipadoheader` command. The reason why I did not do it in the first place is that I was not sure if that command is meant to be used only in the context of `ipacheck` since the features in `ipadoheader` are applicable in many other contexts as well. And if the `ipadoheader` is meant to be used in other contexts it does not make sense to test for these three commands that is a specific requirement to `ipacheck`.

Up to you, but I would be a bit careful to install commands on users' computers instead of prompting them to do so manually. It is not that it wouldn't work, but I wonder if it is practice that is that great and/or appreciated by users. I think it would be different if Stata had a dependency management system like all modern languages, but it doesn't.

And for people without admin access to their computer, a command like `net install` might not work, so the installation cannot be automatically. What we would do on a World Bank computer where only `ssc` can access the internet is to copy the files from the repo to the *ado* folder. As that is a manual work-around for the installation in `ipacheck`, but that manual work-around would not include other packages the installation script includes.

What you do in the end is obviously up to you, I am just providing the reasons behind my suggestion. 

Let me know if you want me to move the code I suggested here into `ipadoheader` or just close this PR if you want to do something completely different.

**Comment by rsandino** [comment]
A solution might be to move the code to ipacheckimport, the code that imports the globals from hfc_inputs to be used in master_check. That ways ipadoheader stays as is and the program check is only run if they are running ipacheck?

**Comment by kbjarkefur** [comment]
@rsandino , that sounds like a great solution to thoughts that I had. Do you want me to update this PR so that the code is included in `ipacheckimport` instead?

**Comment by rsandino** [comment]
That would be great!

**Comment by kbjarkefur** [comment]
@rsandino , I moved the check into `ipacheckimport` in commit 49f7e86.  The new location for this check is indeed the best location.

**Pull request merged**
